SOUTHEAST_ASIAS = [
  BRUNEI = "BRN",
  CAMBODIA = "KHM",
  INDONESIA = "IDN",
  LAOS = "LAO",
  MALAYSIA = "MYS",
  MYANMAR = "MMR",
  PHILIPPINES = "PHL",
  SINGAPORE = "SGP",
  THAILAND = "THA",
  TIMOR_LESTE = "TLS",
  VIETNAM = "VNM",
]

EAST_ASIAS = [
  CHINA = "CHN",
  JAPAN = "JPN",
  MONGOLIA = "MNG",
  SOUTH_KOREA = "KOR",
  NORTH_KOREA = "PRK"
]

COUNTRIES = SOUTHEAST_ASIAS + EAST_ASIAS
