default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: db/cs765-challenge-2-dev

test:
  <<: *default
  database: db/cs765-challenge-2-test

production:
  <<: *default
  database: db/cs765-challenge-2-prod
